### ISSUE TITLE
Could not find a version that satisfies the requirement ppextensions

### ISSUE THREAD

**Issue by Dee-Pac** [paypal/PPExtensions#15]
LM-SJN-00876784:~ dmohanakumarchan$ pip install ppextensions
Collecting ppextensions
  Could not fetch URL https://pypi.python.org/simple/ppextensions/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) - skipping
  Could not find a version that satisfies the requirement ppextensions (from versions: )
No matching distribution found for ppextensions

**Comment by Dee-Pac** [comment]
@ayushiagarwal @praveenkanamarlapudi Am I missing something?

**Comment by praveenkanamarlapudi** [comment]
it's a [pip version and ssl issue](https://github.com/pypa/pip/issues/5236). 

Upgrade pip and try installing again.
```curl https://bootstrap.pypa.io/get-pip.py | python```

**Comment by Dee-Pac** [comment]
`MAC:lime dmohanakumarchan$ curl https://bootstrap.pypa.io/get-pip.py | python`
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1604k  100 1604k    0     0  1040k      0  0:00:01  0:00:01 --:--:-- 1040k
Collecting pip
  Downloading https://files.pythonhosted.org/packages/5f/25/e52d3f31441505a5f3af41213346e5b6c221c9e086a166f3703d2ddaf940/pip-18.0-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 1.6MB/s 
Collecting wheel
  Downloading https://files.pythonhosted.org/packages/81/30/e935244ca6165187ae8be876b6316ae201b71485538ffac1d718843025a9/wheel-0.31.1-py2.py3-none-any.whl (41kB)
    100% |████████████████████████████████| 51kB 1.9MB/s 
Installing collected packages: pip, wheel
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
Successfully installed pip-18.0 wheel-0.31.1
```

`MAC:lime dmohanakumarchan$ pip install ppextensions`

```
Collecting ppextensions
  Downloading https://files.pythonhosted.org/packages/a4/29/d16623a0f91e57da79bb870bdeeee43d32bf921ecf7086198d810620ea81/ppextensions-0.0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/p9/v9t3kcn92vj9055qsg1pt9pc392gjp/T/pip-install-5fC2Bp/ppextensions/setup.py", line 14, in <module>
        README = open(os.path.join(here, 'README.md'), encoding='utf-8').read()
    TypeError: 'encoding' is an invalid keyword argument for this function
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/p9/v9t3kcn92vj9055qsg1pt9pc392gjp/T/pip-install-5fC2Bp/ppextensions/
```

Is this again related my laptop?

**Comment by Dee-Pac** [comment]
@ayushiagarwal @aashish-sheshadri 
Please have a look at this [Build Log via CI](https://travis-ci.com/paypal/PPExtensions/builds/82836433)
